apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::716966774056:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ONS3O6E03WWU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::716966774056:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-07T08:41:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1378"
  uid: 21d53c9d-9c4b-4e7f-80c5-cd10a3ff62ef
